// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Training.Database;

#nullable disable

namespace Training.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209165416_Mig")]
    partial class Mig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Training.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0108af94-deda-496c-b9b3-33c0ab507c48"),
                            Name = "Al-Jabari"
                        },
                        new
                        {
                            Id = new Guid("298afab7-02cb-4d3c-943f-a0a16511b5ba"),
                            Name = "Al-Hroub"
                        },
                        new
                        {
                            Id = new Guid("1b153585-b325-4374-817b-03da591d889a"),
                            Name = "Al-Amleh"
                        });
                });

            modelBuilder.Entity("Training.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("364d0d40-8fa0-45d4-adc1-c9caca868b62"),
                            CategoryId = new Guid("0108af94-deda-496c-b9b3-33c0ab507c48"),
                            Name = "Basel",
                            Price = 1
                        },
                        new
                        {
                            Id = new Guid("5b6bf0de-4275-43b4-9545-59a46b437ac9"),
                            CategoryId = new Guid("298afab7-02cb-4d3c-943f-a0a16511b5ba"),
                            Name = "Haitham",
                            Price = 1
                        },
                        new
                        {
                            Id = new Guid("a000294e-6be2-473d-a933-ab964c32dc34"),
                            CategoryId = new Guid("1b153585-b325-4374-817b-03da591d889a"),
                            Name = "Belal",
                            Price = 1
                        });
                });

            modelBuilder.Entity("Training.Models.Product", b =>
                {
                    b.HasOne("Training.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
